/* BirdNET3_Geo_Fullstack_Web v0.2.2. Frontend 100% estático; ONNX en Web Worker. */
const APP_VERSION='0.2.2', BUILD_ID='20261008-022';
const $=id=>document.getElementById(id);
const clamp=(x,a,b)=>Math.min(b,Math.max(a,x));
const fmt=(v,precise=false)=>{v=Math.max(0,Number(v)||0);const h=Math.floor(v/3600),m=Math.floor(v%3600/60),s=Math.floor(v%60);return (h?`${h}:`:'')+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')+(precise?'.'+String(Math.round((v%1)*100)).padStart(2,'0'):'')};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const audio=$('audioPlayer'),canvas=$('spectrum'),ctx=canvas.getContext('2d'),mini=$('overview'),miniCtx=mini.getContext('2d');
let cfg={};let file=null,objectUrl=null,mono=null,duration=0,rows=[],visible=[],selectedId=null,view=[0,1],frequencies=[0,12000],axis='mel',interaction='box',pointer=null,plotImage=null,renderCounter=0;
let progressPercent=0;let selectedRow=null,segmentEnd=null,sortKey='start',sortAsc=true,recordedLogs=[],busy=false,currentJob=0,playRAF=null,provider='sin cargar',geoStatus='Geo: pendiente',workerMessageSeq=0;
const W=new Worker(new URL('./onnx.worker.js?v=0.2.2',import.meta.url));const pending=new Map();
function log(message,type='info'){const s=`${new Date().toISOString()} [${type.toUpperCase()}] ${message}`;recordedLogs.push(s);if(recordedLogs.length>2000)recordedLogs.shift();const diag=$('diagnosticText');if(diag)diag.textContent=recordedLogs.join('\n');if(type==='error')console.error(s);else console.info(s)}
function workerCall(message,onProgress){return new Promise((resolve,reject)=>{const id=++workerMessageSeq;pending.set(id,{resolve,reject,onProgress});W.postMessage({id,...message})})}
W.onmessage=e=>{const m=e.data,call=pending.get(m.id);if(!call)return;if(m.type==='trace'){log('[WORKER] '+m.message,m.level||'info');return}if(m.type==='stage'||m.type==='info'||m.type==='provider'){call.onProgress?.(m);return}if(m.type==='result'){pending.delete(m.id);m.ok?call.resolve(m):call.reject(new Error(m.error||'Error desconocido en ONNX'))}};
W.onerror=e=>{log(`Error del worker: ${e.message}`,'error');showError(`Error del motor ONNX: ${e.message}`);for(const c of pending.values())c.reject(new Error(e.message));pending.clear()};
function parseYaml(text){const root={},stack=[{indent:-1,obj:root}];for(const original of text.split(/\r?\n/)){if(!original.trim()||/^\s*#/.test(original))continue;const m=original.match(/^(\s*)([\w-]+):(?:\s*(.*))?$/);if(!m)continue;const indent=m[1].length,key=m[2];let raw=(m[3]||'').trim();raw=raw.replace(/\s+#.*$/,'').trim();while(stack.length>1&&stack.at(-1).indent>=indent)stack.pop();const dst=stack.at(-1).obj;if(!raw){dst[key]={};stack.push({indent,obj:dst[key]});continue}let val=raw;if(raw==='true')val=true;else if(raw==='false')val=false;else if(raw==='null')val=null;else if(/^[-+]?\d+(\.\d+)?$/.test(raw))val=Number(raw);else if(/^".*"$/.test(raw)){try{val=JSON.parse(raw)}catch{}}else if(/^'.*'$/.test(raw))val=raw.slice(1,-1);dst[key]=val;}return root}
async function loadConfig(){try{const r=await fetch('./config.yaml?v=0.2.2',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);cfg=parseYaml(await r.text());}catch(e){log('No se pudo cargar config.yaml: '+e.message,'error');cfg={}};
 const conf=cfg.inference||{};$('window').value=conf.window_seconds??5;$('overlap').value=conf.overlap_seconds??1;$('threshold').value=conf.visualization_threshold??.1;$('inferenceMin').value=conf.min_confidence??.01;$('topK').value=conf.top_k??100;$('zone').value=cfg.metadata?.default_timezone||'-05:00';const priorKeep=localStorage.getItem('birdnet_keep_models_v022')??localStorage.getItem('birdnet_keep_models_v021');$('keepModels').checked=priorKeep===null?(cfg.models?.keep_local??true):priorKeep==='true';$('useGeo').checked=cfg.geo?.enabled??true;}
function showProgress(stage,percent=null){if(percent!==null)progressPercent=Math.max(progressPercent,clamp(percent,0,100));$('fileInfo').hidden=true;$('fileProgress').hidden=false;$('phase').textContent=stage;$('phasePct').textContent=percent===null?'':`${Math.round(progressPercent)}%`;$('progressFill').style.width=progressPercent+'%';$('progressText').textContent=(file?.name||'')+(stage?' · '+stage:'');}
function endProgress(){ $('fileProgress').hidden=true;$('fileInfo').hidden=false;if(file)$('fileInfo').innerHTML=`<b>${esc(file.name)}</b><small>${(file.size/1048576).toFixed(2)} MB · ${(duration/60).toFixed(2)} min · ${esc(provider)}</small>` }
function showError(e){const m=e?.stack||e?.message||String(e);log(m,'error');$('diagnostics').hidden=false;$('diagnostics').open=true;showProgress('Error en el análisis',0);$('progressText').textContent='Error · abre Diagnóstico o descarga el registro';$('analyze').disabled=false;busy=false;}
function getWeek(date){if(!date)return null;const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(date);if(!match)return null;const d=new Date(Date.UTC(+match[1],+match[2]-1,+match[3]));if(isNaN(d)||d.getUTCFullYear()!==+match[1]||d.getUTCMonth()!==+match[2]-1||d.getUTCDate()!==+match[3])return null;const start=new Date(Date.UTC(d.getUTCFullYear(),0,1));const day=Math.floor((d-start)/86400000);return clamp(Math.floor(day/365*48)+1,1,48)}
function nameMetadata(name){const base=name.replace(/\.[^.]+$/,'');const out={date:'',hour:'',zone:'-05:00',lat:'',lon:'',week:''};let m=base.match(/(20\d{2})(\d{2})(\d{2})[T_ -]?(\d{2})(\d{2})(\d{2})([+-]\d{2}(?::?\d{2})?)/);if(!m)m=base.match(/(20\d{2})(\d{2})(\d{2})[T_ -]?(\d{2})(\d{2})(\d{2})/);if(m){out.date=`${m[1]}-${m[2]}-${m[3]}`;out.hour=`${m[4]}:${m[5]}:${m[6]}`;if(m[7]){const x=m[7].replace(':','');out.zone=x.slice(0,3)+':'+(x.slice(3)||'00')}out.week=getWeek(out.date)||''}
 let c=base.match(/\[\s*([+-]?\d{1,2}\.\d+)\s*[,; ]+\s*([+-]?\d{1,3}\.\d+)\s*\]/);if(!c)c=base.match(/\[\s*([+-]?\d{1,2}\.\d+)\s+([+-]\d{1,3}\.\d+)\s*\]/);if(!c)c=base.match(/\[\s*([+-]?\d{1,2}\.\d+)\s*([+-]\d{1,3}\.\d+)\s*\]/);if(c){out.lat=c[1];out.lon=c[2]}
 return out}
function setMetadata(meta){for(const [k,id] of Object.entries({date:'date',hour:'hour',zone:'zone',lat:'lat',lon:'lon',week:'week'})){$(id).value=meta[k]??''}}
function metadata(){const lat=$('lat').value.trim(),lon=$('lon').value.trim();const week=+$('week').value;return {lat:lat!==''&&Number.isFinite(+lat)&&Math.abs(+lat)<=90?+lat:null,lon:lon!==''&&Number.isFinite(+lon)&&Math.abs(+lon)<=180?+lon:null,week:Number.isInteger(week)&&week>=1&&week<=48?week:null}}
async function decodeAudio(file){const data=await file.arrayBuffer(),Context=window.AudioContext||window.webkitAudioContext;const ac=new Context();let buf;try{buf=await ac.decodeAudioData(data)}finally{await ac.close()}const sr=cfg.audio?.sample_rate||32000;const off=new OfflineAudioContext(1,Math.ceil(buf.duration*sr),sr);const source=off.createBufferSource();source.buffer=buf;source.connect(off.destination);source.start();const rendered=await off.startRendering();return new Float32Array(rendered.getChannelData(0))}
async function handleFile(f){if(!f)return;if(busy){log('Se intentó cargar otro archivo durante un análisis; espere a que termine.','warn');return}file=f;progressPercent=0;rows=[];visible=[];selectedId=null;selectedRow=null;segmentEnd=null;$('detectionsBody').innerHTML='<tr class="none"><td colspan="7">Procesando audio...</td></tr>';$('detectionCount').textContent='0 detecciones';$('specPlaceholder').hidden=true;$('analyze').disabled=true;$('exportTxt').disabled=true;$('exportCsv').disabled=true;$('refresh').disabled=true;setMetadata(nameMetadata(file.name));$('keepModels').disabled=false;showProgress('Abriendo audio',8);
 try{if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(file);audio.src=objectUrl;audio.load();mono=await decodeAudio(file);duration=mono.length/(cfg.audio?.sample_rate||32000);if(!duration)throw Error('El archivo no tiene audio');view=[0,duration];frequencies=[0,cfg.spectrogram?.max_frequency_hz||12000];$('durationLabel').textContent=`${fmt(duration)} · 32 kHz`;showProgress('Calculando espectrograma',14);scheduleSpec();drawOverview();$('analyze').disabled=false;$('refresh').disabled=false;await runInference();}
 catch(err){showError(err)}}
function getParams(){const win=+$('window').value,over=+$('overlap').value,threshold=+$('inferenceMin').value,topK=+$('topK').value;if(!(win>=1&&win<=20))throw Error('La ventana debe ser de 1 a 20 segundos');if(!(over>=0&&over<win))throw Error('El solapamiento debe ser menor que la ventana');if(!(threshold>=0&&threshold<=1))throw Error('Umbral de inferencia inválido');if(!(topK>=1&&topK<=200))throw Error('Top K debe estar entre 1 y 200');return {window:win,overlap:over,minConfidence:threshold,topK}}
async function runInference(){if(!file||!mono)return;if(busy)return;if(rows.length)progressPercent=0;busy=true;$('analyze').disabled=true;$('uploadBtn').disabled=true;$('audioFile').disabled=true;$('exportTxt').disabled=true;$('exportCsv').disabled=true;const thisJob=++currentJob;
 try{const p=getParams();let cfgModels=cfg.models||{};const local=async(id)=>$(id).files?.[0]?await $(id).files[0].arrayBuffer():null;
 const [la,ll,lg,lgl]=await Promise.all(['localAcoustic','localLabels','localGeo','localGeoLabels'].map(local));
 const m=metadata();const modelUrl=u=>{if(!u)throw Error('Falta URL del modelo en config.yaml');return new URL(u,document.baseURI).href};showProgress('Preparando modelos ONNX',5);log(`Iniciando ${file.name}: ventana=${p.window}, solapamiento=${p.overlap}, top_k=${p.topK}, umbral=${p.minConfidence}`);log(`Fuentes configuradas: acústico=${modelUrl(cfgModels.acoustic_url)} | etiquetas=${modelUrl(cfgModels.acoustic_labels_url)} | geo=${modelUrl(cfgModels.geo_url)} | etiquetasGeo=${modelUrl(cfgModels.geo_labels_url)}`);
 const result=await workerCall({type:'infer',audio:mono,...p,lat:m.lat,lon:m.lon,week:m.week,geoEnabled:$('useGeo').checked,device:cfg.inference?.device||'auto',keep:$('keepModels').checked,
 acousticUrl:modelUrl(cfgModels.acoustic_url),labelsUrl:modelUrl(cfgModels.acoustic_labels_url),geoUrl:modelUrl(cfgModels.geo_url),geoLabelsUrl:modelUrl(cfgModels.geo_labels_url),localAcoustic:la,localLabels:ll,localGeo:lg,localGeoLabels:lgl},(evt)=>{
 if(thisJob!==currentJob)return;
 if(evt.type==='provider'){provider=evt.provider;$('engineLabel').textContent=provider;$('serverStatus').textContent='● '+provider}
 else if(evt.type==='info'){log(evt.message,'warn');$('cacheInfo').textContent=evt.message}
 else if(evt.type==='stage'){const isInfer=evt.kind==='analysis';const pct=isInfer?Math.round(35+(evt.percent||0)*.56):evt.stage?.includes('Descargando')&&evt.stage?.includes('Geo')?92+(evt.percent||0)*.07:evt.stage?.includes('Descargando')?8+(evt.percent||0)*.26:evt.stage?.includes('Geo')?94:32;showProgress(evt.stage,pct)} });
 rows=result.detections.map((r,i)=>({...r,id:i}));geoStatus=result.geoStatus;log(`Inferencia finalizada: ${result.windows} ventanas, ${rows.length} detecciones, ${Math.round(result.durationMs)} ms; ${geoStatus}`);$('geoStatus').textContent='Geo: '+geoStatus;$('cacheInfo').textContent=$('keepModels').checked?'Modelos conservados localmente cuando el navegador lo permite':'Persistencia desactivada';endProgress();checkCache();renderTable();redrawPlot();$('analyze').disabled=false;$('exportTxt').disabled=false;$('exportCsv').disabled=false;
 }catch(err){showError(err)}finally{busy=false;$('uploadBtn').disabled=false;$('audioFile').disabled=false;$('analyze').disabled=!mono}}
function sortedRows(){const th=+$('threshold').value||0,q=$('speciesSearch').value.toLowerCase().trim();const raw=$('viewMode').value==='events'?mergedEvents(rows):rows;let r=raw.filter(x=>x.acoustic>=th&&(!q||x.species.toLowerCase().includes(q)||x.common?.toLowerCase().includes(q)));r.sort((a,b)=>{let x=a[sortKey],y=b[sortKey];if(x==null&&y==null)return 0;if(x==null)return 1;if(y==null)return -1;let c=typeof x==='string'?x.localeCompare(y):x-y;return sortAsc?c:-c});return r}
function mergedEvents(data){const group=new Map();for(const r of [...data].sort((a,b)=>a.start-b.start)){const key=r.species;let a=group.get(key);if(!a){a=[];group.set(key,a)}const last=a.at(-1);if(last&&r.start<=last.end+.15){last.end=Math.max(last.end,r.end);last.acoustic=Math.max(last.acoustic,r.acoustic);last.geo=r.geo;last.count++}else a.push({...r,id:`evt-${r.id}`,kind:'ROI estimada',count:1})}return [...group.values()].flat()}
function score(s,geo=false){if(s==null)return '<span class="muted">—</span>';return `<span>${Number(s).toFixed(2)}</span><span class="scorebar ${geo?'geo':''}"><b style="width:${clamp(s,0,1)*100}%"></b></span>`}
function renderTable(){visible=sortedRows();const tbody=$('detectionsBody');if(!visible.length){tbody.innerHTML='<tr class="none"><td colspan="7">No hay detecciones con este filtro.</td></tr>'}else{tbody.innerHTML=visible.map(r=>`<tr data-id="${esc(r.id)}" class="${r.id===selectedId?'active':''}"><td><button class="playrow" data-play="${esc(r.id)}" aria-label="Reproducir o pausar">${selectedRow===r.id&&!audio.paused?'❚❚':'▶'}</button></td><td>${fmt(r.start,true)}</td><td>${fmt(r.end,true)}</td><td title="${esc(r.common)}"><i>${esc(r.species)}</i></td><td>${score(r.acoustic)}</td><td>${score(r.geo,true)}</td><td><span class="pill ${r.kind.includes('ROI')?'group':''}">${esc(r.kind)}</span></td></tr>`).join('')}
 $('detectionCount').textContent=`${visible.length} / ${rows.length} detecciones`;for(const th of document.querySelectorAll('thead th[data-key]')){th.querySelector('i').textContent=th.dataset.key===sortKey?(sortAsc?'↑':'↓'):'↕'}}
function pickRow(id,play=false){const r=visible.find(x=>String(x.id)===String(id))||rows.find(x=>String(x.id)===String(id));if(!r)return;selectedId=r.id;if(play){if(selectedRow===r.id&&!audio.paused){audio.pause();selectedRow=null}else{selectedRow=r.id;segmentEnd=r.end;seek(r.start);audio.play().catch(e=>log('Reproducción bloqueada: '+e.message,'warn'))}}else{seek(r.start)}
 if(r.start<view[0]||r.end>view[1]){const span=view[1]-view[0],a=clamp(r.start-span*.3,0,Math.max(0,duration-span));view=[a,Math.min(duration,a+span)];scheduleSpec()}redrawPlot();renderTable()}
function seek(t){if(!objectUrl)return;if(audio.readyState<1){audio.addEventListener('loadedmetadata',()=>audio.currentTime=clamp(t,0,duration),{once:true})}else audio.currentTime=clamp(t,0,duration);redrawPlot()}
function toggleMainPlay(){if(!objectUrl)return;if(audio.paused){selectedRow=null;segmentEnd=null;audio.play().catch(e=>log(e.message,'warn'))}else audio.pause()}
function downloadText(name,data,type='text/plain;charset=utf-8'){const u=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),2000)}
function exportResults(type){if(!file||!rows.length)return;const name=file.name.replace(/\.[^.]+$/,'');if(type==='txt'){const text=rows.filter(r=>r.acoustic>=+$('threshold').value).map(r=>`${r.start.toFixed(3)}\t${r.end.toFixed(3)}\t${r.species} ${r.acoustic.toFixed(2)}`).join('\n');downloadText(`${name}_BirdNET3_Audacity.txt`,text+'\n')}else{const escCsv=s=>'"'+String(s??'').replace(/"/g,'""')+'"';const body=['inicio_s,fin_s,nombre_cientifico,nombre_comun,score_acustico,score_geo,tipo',...rows.map(r=>[r.start.toFixed(3),r.end.toFixed(3),escCsv(r.species),escCsv(r.common),r.acoustic.toFixed(6),r.geo==null?'':r.geo.toFixed(6),escCsv(r.kind)].join(','))].join('\n');downloadText(`${name}_BirdNET3.csv`,'\uFEFF'+body+'\n','text/csv;charset=utf-8')}}
// ----- Espectrograma adaptativo: FFT del audio original por región visible -----
const mel=f=>2595*Math.log10(1+f/700),invMel=m=>700*(10**(m/2595)-1);
const ramps=[[4,6,24],[35,12,77],[83,18,120],[141,29,94],[210,66,61],[255,144,49],[255,230,129]];
function rgb(t){t=clamp(t,0,1)*(ramps.length-1);const i=Math.min(ramps.length-2,Math.floor(t)),a=t-i;return ramps[i].map((v,j)=>Math.round(v*(1-a)+ramps[i+1][j]*a))}
function fft(samples){const n=samples.length;let re=new Float32Array(n),im=new Float32Array(n);for(let i=0;i<n;i++){let j=0,k=i;for(let b=n>>1;b;b>>=1){j=(j<<1)|(k&1);k>>=1}re[j]=samples[i]}
 for(let size=2;size<=n;size*=2){const half=size/2,angle=-2*Math.PI/size;for(let start=0;start<n;start+=size){for(let j=0;j<half;j++){const th=angle*j,cs=Math.cos(th),sn=Math.sin(th),i0=start+j,i1=i0+half,tr=cs*re[i1]-sn*im[i1],ti=cs*im[i1]+sn*re[i1];re[i1]=re[i0]-tr;im[i1]=im[i0]-ti;re[i0]+=tr;im[i0]+=ti}}}const power=new Float32Array(n/2);for(let i=0;i<n/2;i++)power[i]=10*Math.log10(1e-10+re[i]*re[i]+im[i]*im[i]);return power}
const plotMargin={left:59,right:13,top:13,bottom:28};
function resizeCanv(el){const rect=el.getBoundingClientRect();if(rect.width<10||rect.height<10)return false;const w=Math.round(rect.width),h=Math.round(rect.height);if(w!==el.width||h!==el.height){el.width=w;el.height=h;return true}return false}
function mapFreq(frac){if(axis==='linear')return frequencies[0]+(frequencies[1]-frequencies[0])*frac;const a=mel(frequencies[0]),b=mel(frequencies[1]);return invMel(a+(b-a)*frac)}
function freqFraction(f){if(axis==='linear')return (f-frequencies[0])/(frequencies[1]-frequencies[0]);return (mel(f)-mel(frequencies[0]))/(mel(frequencies[1])-mel(frequencies[0]))}
function getPlotRect(){return {x:plotMargin.left,y:plotMargin.top,w:canvas.width-plotMargin.left-plotMargin.right,h:canvas.height-plotMargin.top-plotMargin.bottom}}
function drawOverview(){if(!mono)return;resizeCanv(mini);const w=mini.width,h=mini.height;if(w<=0)return;miniCtx.fillStyle='#0d1b36';miniCtx.fillRect(0,0,w,h);const block=Math.ceil(mono.length/w);miniCtx.fillStyle='#7aaafa';for(let x=0;x<w;x++){const start=x*block,end=Math.min(mono.length,start+block);let peak=0;for(let k=start;k<end;k+=Math.max(1,Math.round(block/100)))peak=Math.max(peak,Math.abs(mono[k]));const z=Math.max(1,peak*h*.42);miniCtx.fillRect(x,h/2-z,1,z*2)}drawOverviewWindow()}
function drawOverviewWindow(){if(!duration)return;const l=view[0]/duration*100,w=(view[1]-view[0])/duration*100;$('viewWindow').style.left=l+'%';$('viewWindow').style.width=w+'%';$('timeline').textContent=`${fmt(view[0])} / ${fmt(duration)}`}
async function makePlot(token){if(!mono||!resizeCanv(canvas)&&plotImage&&token<renderCounter)return;const rect=getPlotRect(),width=Math.max(1,Math.round(rect.w)),height=Math.max(1,Math.round(rect.h));const span=view[1]-view[0];const fftSize=span<20?4096:span<120?2048:1024;const sr=cfg.audio?.sample_rate||32000;
 $('specQuality').textContent=`STFT ${fftSize} · ${span<duration?'detalle recalculado':'vista general'}`;
 const smallW=Math.max(1,Math.min(width,1200)),smallH=Math.max(1,Math.min(height,460));const value=new Float32Array(smallW*smallH),windowFn=new Float32Array(fftSize);for(let i=0;i<fftSize;i++)windowFn[i]=.5-.5*Math.cos(2*Math.PI*i/(fftSize-1));
 let max=-100;for(let x=0;x<smallW;x++){if(token!==renderCounter)return;const t=view[0]+(x+.5)/smallW*span,idx=Math.round(t*sr)-fftSize/2,block=new Float32Array(fftSize);for(let n=0;n<fftSize;n++)block[n]=(mono[clamp(idx+n,0,mono.length-1)]||0)*windowFn[n];const power=fft(block);for(let y=0;y<smallH;y++){const f=mapFreq(1-(y+.5)/smallH);const fi=clamp(Math.round(f*fftSize/sr),0,power.length-1);const val=power[fi];value[y*smallW+x]=val;if(val>max)max=val}if(x%30===0)await new Promise(resolve=>setTimeout(resolve,0))}
 if(token!==renderCounter)return;const off=document.createElement('canvas');off.width=smallW;off.height=smallH;const c=off.getContext('2d'),pic=c.createImageData(smallW,smallH),lo=max-72;for(let i=0;i<value.length;i++){const rgbv=rgb((value[i]-lo)/72),o=i*4;pic.data[o]=rgbv[0];pic.data[o+1]=rgbv[1];pic.data[o+2]=rgbv[2];pic.data[o+3]=255}c.putImageData(pic,0,0);plotImage=off;redrawPlot()}
let redrawTimer=null;function scheduleSpec(){if(!mono)return;resizeCanv(canvas);const id=++renderCounter;clearTimeout(redrawTimer);redrawTimer=setTimeout(()=>makePlot(id).catch(e=>log('Espectrograma: '+e.message,'error')),120);drawOverviewWindow();redrawPlot()}
function tickStep(range,target){const raw=range/target,mag=10**Math.floor(Math.log10(Math.max(raw,1)));return [1,2,5,10].map(x=>x*mag).find(x=>x>=raw)||10*mag}
function redrawPlot(){if(!mono)return;const wasResized=resizeCanv(canvas);if(wasResized){scheduleSpec();return}const p=getPlotRect();if(p.w<=0||p.h<=0)return;ctx.fillStyle='#071022';ctx.fillRect(0,0,canvas.width,canvas.height);if(plotImage)ctx.drawImage(plotImage,p.x,p.y,p.w,p.h);
 ctx.fillStyle='#15243e';ctx.fillRect(0,0,p.x,canvas.height);ctx.fillRect(0,p.y+p.h,canvas.width,plotMargin.bottom);ctx.strokeStyle='#415572';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x,p.y+p.h);ctx.lineTo(p.x+p.w,p.y+p.h);ctx.stroke();ctx.fillStyle='#b4c4de';ctx.font='11px system-ui';ctx.textAlign='right';ctx.textBaseline='middle';const fstep=tickStep(frequencies[1]-frequencies[0],6);for(let f=Math.ceil(frequencies[0]/fstep)*fstep;f<=frequencies[1];f+=fstep){const y=p.y+p.h*(1-freqFraction(f));ctx.fillText(String(Math.round(f)),p.x-9,y);ctx.beginPath();ctx.moveTo(p.x-5,y);ctx.lineTo(p.x,y);ctx.stroke()}
 const step=tickStep(view[1]-view[0],8);ctx.textAlign='center';ctx.textBaseline='top';for(let t=Math.ceil(view[0]/step)*step;t<=view[1]+.001;t+=step){const x=p.x+(t-view[0])/(view[1]-view[0])*p.w;ctx.fillText(fmt(t),x,p.y+p.h+5);ctx.strokeStyle='rgba(255,255,255,.12)';ctx.beginPath();ctx.moveTo(x,p.y);ctx.lineTo(x,p.y+p.h);ctx.stroke()}
 if(selectedId!==null){const r=visible.find(x=>x.id===selectedId)||rows.find(x=>x.id===selectedId);if(r){const l=p.x+(r.start-view[0])/(view[1]-view[0])*p.w,rgt=p.x+(r.end-view[0])/(view[1]-view[0])*p.w;ctx.fillStyle='rgba(70,165,255,.17)';ctx.fillRect(l,p.y,rgt-l,p.h);ctx.strokeStyle='#95dbff';ctx.setLineDash([4,4]);ctx.strokeRect(l,p.y,rgt-l,p.h);ctx.setLineDash([])}}
 if(pointer?.dragged){const r=pointer.box;ctx.fillStyle='rgba(78,158,255,.19)';ctx.fillRect(Math.min(r.x0,r.x1),Math.min(r.y0,r.y1),Math.abs(r.x1-r.x0),Math.abs(r.y1-r.y0));ctx.strokeStyle='#7dd0ff';ctx.setLineDash([5,4]);ctx.strokeRect(Math.min(r.x0,r.x1),Math.min(r.y0,r.y1),Math.abs(r.x1-r.x0),Math.abs(r.y1-r.y0));ctx.setLineDash([])}
 const cursor=p.x+(audio.currentTime-view[0])/(view[1]-view[0])*p.w;if(cursor>=p.x&&cursor<=p.x+p.w){ctx.strokeStyle='#fff5a3';ctx.lineWidth=1.35;ctx.beginPath();ctx.moveTo(cursor,p.y);ctx.lineTo(cursor,p.y+p.h);ctx.stroke()}}
function coords(ev){const r=canvas.getBoundingClientRect();const c=getPlotRect();return {x:clamp(ev.clientX-r.left,c.x,c.x+c.w),y:clamp(ev.clientY-r.top,c.y,c.y+c.h)}}
function timeOfX(x){const p=getPlotRect();return clamp(view[0]+(x-p.x)/p.w*(view[1]-view[0]),0,duration)}
function freqOfY(y){const p=getPlotRect();return mapFreq(1-(y-p.y)/p.h)}
function setView(a,b,fmin=frequencies[0],fmax=frequencies[1]){let width=clamp(b-a,.05,duration);a=clamp(a,0,Math.max(0,duration-width));view=[a,a+width];const maxHz=cfg.spectrogram?.max_frequency_hz||12000;const hz=clamp(fmax-fmin,90,maxHz);fmin=clamp(fmin,0,maxHz-hz);frequencies=[fmin,fmin+hz];scheduleSpec()}
function zoom(factor){const at=(view[0]+view[1])/2,span=(view[1]-view[0])*factor;setView(at-span/2,at+span/2)}
function allView(){setView(0,duration,0,cfg.spectrogram?.max_frequency_hz||12000)}
canvas.addEventListener('pointerdown',e=>{if(!mono)return;canvas.setPointerCapture(e.pointerId);let c=coords(e);pointer={x:c.x,y:c.y,originView:[...view],box:{x0:c.x,y0:c.y,x1:c.x,y1:c.y},dragged:false}});
canvas.addEventListener('pointermove',e=>{if(!pointer)return;let c=coords(e);if(Math.hypot(c.x-pointer.x,c.y-pointer.y)>5)pointer.dragged=true;if(interaction==='pan'&&pointer.dragged){const p=getPlotRect(),dt=(c.x-pointer.x)/p.w*(pointer.originView[1]-pointer.originView[0]);const w=pointer.originView[1]-pointer.originView[0];setView(pointer.originView[0]-dt,pointer.originView[0]-dt+w)}else{pointer.box.x1=c.x;pointer.box.y1=c.y;redrawPlot()}});
canvas.addEventListener('pointerup',e=>{if(!pointer)return;const prev=pointer;pointer=null;const c=coords(e);if(prev.dragged&&interaction==='box'&&Math.abs(c.x-prev.x)>7){const a=timeOfX(Math.min(prev.x,c.x)),b=timeOfX(Math.max(prev.x,c.x));let fmin=frequencies[0],fmax=frequencies[1];if(Math.abs(c.y-prev.y)>12){fmin=Math.min(freqOfY(prev.y),freqOfY(c.y));fmax=Math.max(freqOfY(prev.y),freqOfY(c.y))}setView(a,b,fmin,fmax)}else if(!prev.dragged){segmentEnd=null;selectedRow=null;seek(timeOfX(c.x));renderTable()}redrawPlot()});
canvas.addEventListener('wheel',e=>{if(!mono)return;e.preventDefault();const scale=e.deltaY>0?1.28:.78;const c=coords(e);if(e.shiftKey){const p=getPlotRect(),f=freqOfY(c.y),newSize=(frequencies[1]-frequencies[0])*scale,pos=(f-frequencies[0])/(frequencies[1]-frequencies[0]);setView(...view,f-newSize*pos,f+newSize*(1-pos))}else{const t=timeOfX(c.x),span=(view[1]-view[0])*scale,frac=(t-view[0])/(view[1]-view[0]);setView(t-span*frac,t+span*(1-frac))}},{passive:false});
mini.addEventListener('click',e=>{if(!mono)return;const rect=mini.getBoundingClientRect(),center=clamp((e.clientX-rect.left)/rect.width,0,1)*duration,w=view[1]-view[0];setView(center-w/2,center+w/2)});
audio.addEventListener('timeupdate',()=>{if(segmentEnd!==null&&audio.currentTime>=segmentEnd-.05){audio.pause();segmentEnd=null;selectedRow=null;renderTable()}redrawPlot()});
audio.addEventListener('pause',()=>{$('play').textContent='▶ Reproducir';renderTable()});audio.addEventListener('play',()=>{$('play').textContent='❚❚ Pausar';renderTable()});
// ----- Controls -----
$('uploadBtn').addEventListener('click',()=>$('audioFile').click());$('audioFile').addEventListener('change',e=>{if(e.target.files?.length)handleFile(e.target.files[0]);e.target.value=''});
$('analyze').addEventListener('click',runInference);$('refresh').addEventListener('click',renderTable);$('exportTxt').addEventListener('click',()=>exportResults('txt'));$('exportCsv').addEventListener('click',()=>exportResults('csv'));
$('speciesSearch').addEventListener('input',renderTable);$('threshold').addEventListener('input',renderTable);$('viewMode').addEventListener('change',()=>{selectedId=null;renderTable();redrawPlot()});
$('date').addEventListener('change',()=>{$('week').value=getWeek($('date').value)||''});
document.querySelector('thead').addEventListener('click',e=>{const th=e.target.closest('th[data-key]');if(!th)return;sortAsc=sortKey===th.dataset.key?!sortAsc:true;sortKey=th.dataset.key;renderTable()});
$('detectionsBody').addEventListener('click',e=>{const r=e.target.closest('tr[data-id]');if(r)pickRow(r.dataset.id,!!e.target.closest('[data-play]'))});
$('scale').addEventListener('change',e=>{axis=e.target.value;scheduleSpec()});$('zoomIn').addEventListener('click',()=>zoom(.7));$('zoomOut').addEventListener('click',()=>zoom(1.4));$('viewAll').addEventListener('click',allView);$('play').addEventListener('click',toggleMainPlay);
for(const [id,mode] of [['modeBox','box'],['modePan','pan']])$(id).addEventListener('click',()=>{interaction=mode;$('modeBox').classList.toggle('selected',mode==='box');$('modePan').classList.toggle('selected',mode==='pan');canvas.classList.toggle('pan',mode==='pan')});
$('copyDiagnostic').addEventListener('click',()=>navigator.clipboard?.writeText($('diagnosticText').textContent||''));
function assetUrls(){const m=cfg.models||{};return {acousticUrl:m.acoustic_url,labelsUrl:m.acoustic_labels_url,geoUrl:m.geo_url,geoLabelsUrl:m.geo_labels_url}}
async function checkCache(){try{const response=await workerCall({type:'status',...assetUrls()});$('cacheDetail').textContent=response.assets.map(a=>`${a.name}: ${a.cached?(a.bytes/1048576).toFixed(1)+' MB guardados':'pendiente'}`).join(' · ');const estimate=await navigator.storage?.estimate?.();if(estimate?.usage){$('cacheInfo').textContent=`Caché BirdNET en IndexedDB · uso del origen: ${(estimate.usage/1048576).toFixed(1)} MB · puede limpiarse automáticamente`}}
catch(e){$('cacheDetail').textContent='Caché no disponible: '+e.message;log('Caché: '+e.message,'warn')}}
$('keepModels').addEventListener('change',e=>{localStorage.setItem('birdnet_keep_models_v022',String(e.target.checked));log(`Conservar modelos en navegador: ${e.target.checked?'sí':'no'}`);if(!e.target.checked)$('cacheInfo').textContent='No se leerá ni guardará IndexedDB mientras esté desmarcado. Las copias anteriores continúan hasta Limpiar caché.'});
$('persistStorage').addEventListener('click',async()=>{if(!navigator.storage?.persist){$('cacheInfo').textContent='Este navegador no ofrece solicitud de almacenamiento persistente';return}try{const ok=await navigator.storage.persist();$('cacheInfo').textContent=ok?'Almacenamiento persistente concedido por el navegador':'Solicitud no concedida: la caché funciona pero podría limpiarse automáticamente';log('Almacenamiento persistente: '+ok)}catch(e){log('Persistencia: '+e.message,'warn');$('cacheInfo').textContent='No se pudo solicitar persistencia: '+e.message}});
$('refreshCache').addEventListener('click',checkCache);
$('clearModels').addEventListener('click',async()=>{if(busy)return;try{await workerCall({type:'clear'});$('cacheInfo').textContent='Caché local vaciada';log('Caché local vaciada');await checkCache()}catch(e){showError(e)}});
$('downloadLogs').addEventListener('click',()=>downloadText('BirdNET_Web_diagnostico_v0.2.2.txt',recordedLogs.join('\n')+'\n'));
window.addEventListener('resize',()=>{if(mono){drawOverview();scheduleSpec()}});
window.addEventListener('dragover',e=>e.preventDefault());window.addEventListener('drop',e=>{e.preventDefault();if(e.dataTransfer?.files?.length)handleFile(e.dataTransfer.files[0])});
// La cabecera de diagnóstico debe existir ANTES de toda descarga y mostrar la versión realmente ejecutada.
log(`===== BirdNET3_Geo_Fullstack_Web v${APP_VERSION} | build ${BUILD_ID} =====`);
log(`URL: ${location.href} | origen: ${location.origin} | modo: web estática`);
log(`Navegador: ${navigator.userAgent}`);
log(`WebGPU API: ${navigator.gpu?'presente (compatibilidad aún no verificada)':'no disponible'} | online=${navigator.onLine}`);
log(`Worker solicitado: ${new URL('./onnx.worker.js?v=0.2.2',import.meta.url).href}`);
window.addEventListener('unhandledrejection',e=>log(`Promesa sin capturar: ${e.reason?.stack||e.reason}`,'error'));
window.addEventListener('error',e=>log(`Error global: ${e.message} @ ${e.filename}:${e.lineno}`,'error'));
await loadConfig();
log(`Config: version=${cfg.project?.version||'no declarada'}; fuente acústica=${cfg.models?.acoustic_url||'NO DEFINIDA'}`);
if(cfg.project?.version!==APP_VERSION)log(`AVISO: versión de config.yaml ${cfg.project?.version} distinta de JS ${APP_VERSION}; publica todo el ZIP nuevo.`, 'warn');
$('serverStatus').textContent=`● Web v${APP_VERSION} · ONNX local`;$('geoStatus').textContent='Geo: esperando audio';log('Aplicación inicializada, esperando audio.');checkCache();
